version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/tossmilestone/crawlgo
    steps:
      - checkout

      - run: make setup
      - run: make ci
